### PR TITLE
Fix button font

### PR DESCRIPTION
**Pull request by andrew-vancil**

### CODE REVIEW

**Comment by andrew-vancil** [comment]
I added a line to the css to hopefully default to sans-serif if the user doesn't have the specific font. @cole-brokamp if you knit and look at it now, do you still see the "Source Code Pro" font that you set or do you see the default sans-serif font? I don't know if the line I added supersedes the specific font or sets a default backup

**Review by cole-brokamp — COMMENTED** [review]
I think I found a way to embed a fixed-width font using pkgdown.  Let me know if that displays OK for you.

**Comment by cole-brokamp** [comment]
@andrew-vancil, give this one a spin.  i'm curious if setting font directly in css works now that pkgdown is installing it

**Comment by andrew-vancil** [comment]
It all looks to be working to me, no weird oval on the button and proper font. If you're cool with it, I can squash and merge

**Comment by cole-brokamp** [comment]
nice!  yes, thanks!

**Pull request merged**
